# Generated by Django 2.1.1 on 2018-09-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stockHistData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('date', models.DateField()),
                ('open', models.CharField(max_length=16)),
                ('high', models.CharField(max_length=16)),
                ('close', models.CharField(max_length=16)),
                ('low', models.CharField(max_length=16)),
                ('volume', models.CharField(max_length=16)),
                ('price_change', models.CharField(max_length=16)),
                ('p_change', models.CharField(max_length=16)),
                ('ma5', models.CharField(max_length=16)),
                ('ma10', models.CharField(max_length=16)),
                ('ma20', models.CharField(max_length=16)),
                ('v_ma5', models.CharField(max_length=16)),
                ('v_ma10', models.CharField(max_length=16)),
                ('v_ma20', models.CharField(max_length=16)),
                ('turnover', models.CharField(default='NULL', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='stockReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=64)),
                ('eps', models.CharField(max_length=32)),
                ('eps_yoy', models.CharField(max_length=32)),
                ('bvps', models.CharField(max_length=32)),
                ('roe', models.CharField(max_length=32)),
                ('epcf', models.CharField(max_length=32)),
                ('net_profits', models.CharField(max_length=32)),
                ('profits_yoy', models.CharField(max_length=32)),
                ('distrib', models.CharField(max_length=64)),
                ('report_date', models.CharField(max_length=16)),
                ('season', models.CharField(max_length=16)),
            ],
        ),
    ]
