# Generated by Django 2.1.1 on 2018-09-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userStrategies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=16)),
                ('strategyName', models.CharField(max_length=32)),
                ('strategyScript', models.CharField(max_length=4096)),
                ('createTime', models.DateField()),
                ('lastEditTime', models.DateField()),
                ('status', models.CharField(max_length=16)),
            ],
        ),
    ]
