# Generated by Django 2.1.1 on 2018-09-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Strategies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstrategies',
            name='id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
