# Generated by Django 2.1.1 on 2018-09-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Strategies', '0002_auto_20180920_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstrategies',
            name='createTime',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userstrategies',
            name='lastEditTime',
            field=models.DateField(auto_now=True),
        ),
    ]
