# Generated by Django 2.0.6 on 2018-07-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lastNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashid', models.CharField(max_length=64, unique=True)),
                ('classify', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('time', models.DateTimeField()),
                ('url', models.URLField(max_length=256)),
                ('content', models.TextField(max_length=4096)),
                ('searchlization', models.CharField(default='N', max_length=2)),
            ],
        ),
    ]
